apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: standard-pods
  namespace: argo
  labels:
    team: deploy-platform
    product: engineering-productivity
    project: argo
spec:
  entrypoint: main
  templates:
  - name: echo
    inputs:
      parameters:
      - name: sleep
        value: "5"
    container:
      image: alpine:3.7
      command: [sleep, "{{inputs.parameters.sleep}}"]
  - name: main
    dag:
      tasks:
      - name: buddy
        template: echo
      - name: pod26
        dependencies: [buddy]
        template: echo
      - name: pod15
        dependencies: [pod26]
        template: echo
      - name: pod17
        dependencies: [pod26]
        template: echo
      - name: pod25
        dependencies: [pod26]
        template: echo