apiVersion: argoproj.io/v1alpha1               # Create a rollout resource
kind: Rollout
metadata:
  name: guestbook-ui-rollout
  labels:
    product: engineering-productivity
    team: deploy-platform
    project: guestbook
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
        product: engineering-productivity
        team: deploy-platform
        project: guestbook
        version: something
    spec:
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
          name: guestbook-ui
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: guestbook-ui
            - secretRef:
                name: guestbook-ui
  strategy:
    blueGreen:
      activeService: guestbook-ui
      previewService: guestbook-ui-preview
