apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: guestbook-ui
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: guestbook-ui-rollout
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
