apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  labels:
    product: engineering-productivity
    team: deploy-platform
    project: guestbook
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: guestbook-ui
    role: active
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui-preview
  labels:
    product: engineering-productivity
    team: deploy-platform
    project: guestbook
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: guestbook-ui
    role: preview