apiVersion: argoproj.io/v1alpha1               # Create a rollout resource
kind: Rollout
metadata:
  name: guestbook-ui-rollout
spec:
  replicas: 5
  selector:
    matchLabels:
      app: guestbook-ui
  workloadRef:                                 # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: guestbook-ui
    scaleDown: onsuccess
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 10s}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  labels:
    product: engineering-productivity
    team: deploy-platform
    project: guestbook
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
        product: engineering-productivity
        team: deploy-platform
        project: guestbook
        version: something
    spec:
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
          name: guestbook-ui
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: guestbook-ui
            - secretRef:
                name: guestbook-ui
