apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: standard-pods
  namespace: argo
  labels:
    team: deploy-platform
    product: engineering-productivity
    project: argo
spec:
  arguments:
    parameters:
      - name: application-name
      - name: revision
  entrypoint: main
  templates:
  - name: echo
    inputs:
      parameters:
      - name: sleep
        value: "5"
    container:
      image: alpine:3.7
      command: [sleep, "{{inputs.parameters.sleep}}"]
  - name: main
    dag:
      tasks:
      - name: buddy
        template: echo
      - name: pod26
        dependencies: [buddy]
        arguments:
          parameters:
            - name: application-name
              value: "{{ workflow.parameters.application-name }}"
            - name: revision
              value: "{{ workflow.parameters.revision }}"
        templateRef:
          name: argocd-sync-and-wait
          template: argocd-sync-and-wait
      - name: pod15
        dependencies: [pod26]
        template: echo
      - name: pod17
        dependencies: [pod26]
        template: echo
      - name: pod25
        dependencies: [pod26]
        template: echo
      - name: continue
        dependencies: [pod15, pod17, pod25]
        activeDeadlineSeconds: 120
        template: judgement

  - name: judgement
    suspend: {}
